import React from "react";
import { StickyScroll } from "../components/ui/sticky-scroll-reveal.jsx";

const content = [
  {
    title: "AI-Powered Interviews",
    description: (
      <p className="text-lg text-gray-200 leading-relaxed">
        Engage in realistic interview simulations with our advanced AI. <span className="font-semibold text-emerald-300">Practice anytime, anywhere</span> without the pressure of human judgment. Our AI adapts to your responses, providing <span className="font-semibold text-amber-300">personalized feedback</span> to help you improve your communication skills and confidence.
      </p>
    ),
    content: (
      <div className="flex h-full w-full items-center justify-center bg-[linear-gradient(to_bottom_right,var(--indigo-500),var(--purple-500))] text-white">
        <img
          src="https://omdia.tech.informa.com/-/media/tech/omdia/omdia-website-enhancement-oct-2023/ai-coverage-2.jpg?rev=56e6f88de6774db290c5069e65788bd1"
          className="h-full w-full object-cover opacity-90"
          alt="AI interview"
        />
      </div>
    ),
  },
  {
    title: "Smart Resume Creation",
    description: (
      <p className="text-lg text-gray-200 leading-relaxed">
        Let our AI craft the perfect resume from your details. <span className="font-semibold text-cyan-300">Automatically format</span> your experience and skills into a professional layout. The system <span className="font-semibold text-purple-300">optimizes keywords</span> for applicant tracking systems, increasing your chances of getting noticed by recruiters.
      </p>
    ),
    content: (
      <div className="flex h-full w-full items-center justify-center bg-[linear-gradient(to_bottom_right,var(--indigo-500),var(--purple-500))] text-white">
        <img
          src="https://media.licdn.com/dms/image/v2/D5612AQHiyWWGuGLhFg/article-cover_image-shrink_720_1280/article-cover_image-shrink_720_1280/0/1733814700081?e=2147483647&v=beta&t=NQeMb2OoFxWjRCRgp8JYA8wc_06g_rYr7YDvV9zORIY"
          className="h-full w-full object-cover opacity-90"
          alt="AI interview"
        />
      </div>
    ),
  },
  {
    title: "AI-Generated Quizzes",
    description: (
      <p className="text-lg text-gray-200 leading-relaxed">
        Test your knowledge with <span className="font-semibold text-red-300">personalized quizzes</span> generated by our AI. The system adapts to your skill level, creating questions that challenge you appropriately. <span className="font-semibold text-lime-300">Instant feedback</span> helps you identify areas for improvement and track your progress over time.
      </p>
    ),
    content: (
      <div className="flex h-full w-full items-center justify-center text-white">
        <img
          src="https://9434986.fs1.hubspotusercontent-na1.net/hubfs/9434986/33.%20Top%20X%20AI%20Quiz%20Generator%20Tools%20and%20Apps%20to%20Try%20in%202024%20-%20cover.jpg"
          className="h-full w-full object-cover opacity-90"
          alt="Quiz"
        />
      </div>
    ),
  },
  {
    title: "Custom Interview Builder",
    description: (
      <p className="text-lg text-gray-200 leading-relaxed">
        Create <span className="font-semibold text-yellow-300">tailored interview experiences</span> by specifying any topic or job role. Our AI generates relevant questions and scenarios to match your needs. Perfect for <span className="font-semibold text-blue-300">niche positions</span> or specialized skills that standard interviews don't cover.
      </p>
    ),
    content: (
      <div className="flex h-full w-full items-center justify-center text-white">
        <img
          src="https://images.unsplash.com/photo-1522202176988-66273c2fd55f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1471&q=80"
          className="h-full w-full object-cover opacity-90"
          alt="Custom interview"
        />
      </div>
    ),
  },
];

export function ScrollerComponent() {
  return (
    <div className="w-[80vw] py-4 mt-[10vh]">
      <StickyScroll content={content} />
    </div>
  );
}